# Recommender system :

- A recommender system, or a recommendation system  is a subclass of information filtering system that provide suggestions for items that are most pertinent to a particular user.
- Typically, the suggestions refer to various decision-making processes, such as what product to purchase, what music to listen to, or what online news to read.


- Recommender systems are particularly useful when an individual needs to choose an item from a potentially overwhelming number of items that a service may offer.


- Recommender systems are used in a variety of areas, with commonly recognised examples taking the form of playlist generators for video and music services, product recommenders for online stores, or content recommenders for social media platforms and open web content recommenders.

- These systems can operate using a single input, like music, or multiple inputs within and across platforms like news, books and search queries.
- There are also popular recommender systems for specific topics like restaurants and online dating.
- Recommender systems have also been developed to explore research articles and experts, collaborators, and financial services.

### Overview

- Recommender systems usually make use of either or both collaborative filtering and content-based filtering (also known as the personality-based approach), as well as other systems such as knowledge-based systems. 



- Collaborative filtering approaches build a model from a user's past behavior (items previously purchased or selected and/or numerical ratings given to those items) as well as similar decisions made by other users. 
- This model is then used to predict items (or ratings for items) that the user may have an interest in. 



- Content-based filtering approaches utilize a series of discrete, pre-tagged characteristics of an item in order to recommend additional items with similar properties.



- We can demonstrate the differences between collaborative and content-based filtering by comparing two early music recommender systems – Last.fm and Pandora Radio.



- Last.fm creates a "station" of recommended songs by observing what bands and individual tracks the user has listened to on a regular basis and comparing those against the listening behavior of other users. 


- Last.fm will play tracks that do not appear in the user's library, but are often played by other users with similar interests.
- As this approach leverages the behavior of users, it is an example of a collaborative filtering technique.




- Pandora uses the properties of a song or artist (a subset of the 400 attributes provided by the Music Genome Project) to seed a "station" that plays music with similar properties. 
- User feedback is used to refine the station's results, deemphasizing certain attributes when a user "dislikes" a particular song and emphasizing other attributes when a user "likes" a song. This is an example of a content-based approach.



- Each type of system has its strengths and weaknesses.
- In the above example, Last.fm requires a large amount of information about a user to make accurate recommendations.
- This is an example of the cold start problem, and is common in collaborative filtering systems.
- Whereas Pandora needs very little information to start, it is far more limited in scope (for example, it can only make recommendations that are similar to the original seed).

## Approaches

### Collaborative filtering

   
- Collaborative filtering is based on the assumption that people who agreed in the past will agree in the future, and that they will like similar kinds of items as they liked in the past.
- The system generates recommendations using only information about rating profiles for different users or items. 
- By locating peer users/items with a rating history similar to the current user or item, they generate recommendations using this neighborhood. 
- Collaborative filtering methods are classified as memory-based and model-based. 
- A well-known example of memory-based approaches is the user-based algorithm, while that of model-based approaches is Matrix factorization (recommender systems).


- A key advantage of the collaborative filtering approach is that it does not rely on machine analyzable content and therefore it is capable of accurately recommending complex items such as movies without requiring an "understanding" of the item itself.
- Many algorithms have been used in measuring user similarity or item similarity in recommender systems. For example, the k-nearest neighbor (k-NN) approach and the Pearson Correlation as first implemented by Allen.


- When building a model from a user's behavior, a distinction is often made between explicit and implicit forms of data collection.


- Examples of explicit data collection include the following:

    - Asking a user to rate an item on a sliding scale.
    - Asking a user to search.
    - Asking a user to rank a collection of items from favorite to least favorite.
    - Presenting two items to a user and asking him/her to choose the better one of them.
    - Asking a user to create a list of items that he/she likes 
    
- Examples of implicit data collection include the following:
    - Observing the items that a user views in an online store.
    - Analyzing item/user viewing times.
    - Keeping a record of the items that a user purchases online.
    - Obtaining a list of items that a user has listened to or watched on his/her computer.
    - Analyzing the user's social network and discovering similar likes and dislikes.
  
  
- Collaborative filtering approaches often suffer from three problems: cold start, scalability, and sparsity.

    - Cold start:
        - For a new user or item, there isn't enough data to make accurate recommendations. Note: one commonly implemented solution to this problem is the Multi-armed bandit algorithm.
    - Scalability: 
        - There are millions of users and products in many of the environments in which these systems make recommendations. Thus, a large amount of computation power is often necessary to calculate recommendations.
    - Sparsity:
        - The number of items sold on major e-commerce sites is extremely large. 
        - The most active users will only have rated a small subset of the overall database. 
        - Thus, even the most popular items have very few ratings.
        
- One of the most famous examples of collaborative filtering is item-to-item collaborative filtering (people who buy x also buy y), an algorithm popularized by Amazon.com's recommender system.


- Many social networks originally used collaborative filtering to recommend new friends, groups, and other social connections by examining the network of connections between a user and their friends.
- Collaborative filtering is still used as part of hybrid systems.


### Content-based filtering

- Another common approach when designing recommender systems is content-based filtering.
- Content-based filtering methods are based on a description of the item and a profile of the user's preferences.
- These methods are best suited to situations where there is known data on an item (name, location, description, etc.), but not on the user.
- Content-based recommenders treat recommendation as a user-specific classification problem and learn a classifier for the user's likes and dislikes based on an item's features.


- In this system, keywords are used to describe the items, and a user profile is built to indicate the type of item this user likes. 
- In other words, these algorithms try to recommend items similar to those that a user liked in the past or is examining in the present.
- It does not rely on a user sign-in mechanism to generate this often temporary profile. In particular, various candidate items are compared with items previously rated by the user, and the best-matching items are recommended.
- This approach has its roots in information retrieval and information filtering research.


- To create a user profile, the system mostly focuses on two types of information:

    1. A model of the user's preference.

    2. A history of the user's interaction with the recommender system.

- Basically, these methods use an item profile (i.e., a set of discrete attributes and features) characterizing the item within the system.
- To abstract the features of the items in the system, an item presentation algorithm is applied.
- A widely used algorithm is the tf–idf representation (also called vector space representation).
- The system creates a content-based profile of users based on a weighted vector of item features. 
- The weights denote the importance of each feature to the user and can be computed from individually rated content vectors using a variety of techniques. 
- Simple approaches use the average values of the rated item vector while other sophisticated methods use machine learning techniques such as Bayesian Classifiers, cluster analysis, decision trees, and artificial neural networks in order to estimate the probability that the user is going to like the item.



- A key issue with content-based filtering is whether the system can learn user preferences from users' actions regarding one content source and use them across other content types. 
- When the system is limited to recommending content of the same type as the user is already using, the value from the recommendation system is significantly less than when other content types from other services can be recommended. 
- For example, recommending news articles based on news browsing is useful. Still, it would be much more useful when music, videos, products, discussions, etc., from different services, can be recommended based on news browsing. To overcome this, most content-based recommender systems now use some form of the hybrid system.


- Content-based recommender systems can also include opinion-based recommender systems. 
- In some cases, users are allowed to leave text reviews or feedback on the items.
- These user-generated texts are implicit data for the recommender system because they are potentially rich resources of both feature/aspects of the item and users' evaluation/sentiment to the item.
- Features extracted from the user-generated reviews are improved meta-data of items, because as they also reflect aspects of the item like meta-data, extracted features are widely concerned by the users. 
- Sentiments extracted from the reviews can be seen as users' rating scores on the corresponding features.
- Popular approaches of opinion-based recommender system utilize various techniques including text mining, information retrieval, sentiment analysis (see also Multimodal sentiment analysis) and deep learning.


### Hybrid recommendations approaches

-  combining collaborative filtering, content-based filtering, and other approaches.
- There is no reason why several different techniques of the same type could not be hybridized.
- Hybrid approaches can be implemented in several ways:
    - by making content-based and collaborative-based predictions separately and then combining them;
    - by adding content-based capabilities to a collaborative-based approach (and vice versa); or 
    - by unifying the approaches into one model 
- Several studies that empirically compare the performance of the hybrid with the pure collaborative and content-based methods and demonstrated that the hybrid methods can provide more accurate recommendations than pure approaches.
- These methods can also be used to overcome some of the common problems in recommender systems such as cold start and the sparsity problem, as well as the knowledge engineering bottleneck in knowledge-based approaches.



- Netflix is a good example of the use of hybrid recommender systems.
- The website makes recommendations by comparing the watching and searching habits of similar users (i.e., collaborative filtering) as well as by offering movies that share characteristics with films that a user has rated highly (content-based filtering).


- Some hybridization techniques include:
    - Weighted: 
        - Combining the score of different recommendation components numerically.
    - Switching: 
        - Choosing among recommendation components and applying the selected one.
    - Mixed: 
        - Recommendations from different recommenders are presented together to give the recommendation.
    - Feature Combination:
        - Features derived from different knowledge sources are combined together and given to a single recommendation algorithm.
    - Feature Augmentation: 
        - Computing a feature or set of features, which is then part of the input to the next technique.
    - Cascade:
        - Recommenders are given strict priority, with the lower priority ones breaking ties in the scoring of the higher ones.
    - Meta-level:
        - One recommendation technique is applied and produces some sort of model, which is then the input used by the next technique.

https://en.wikipedia.org/wiki/Recommender_system

https://en.wikipedia.org/wiki/Association_rule_learning

# Apriori

-  an algorithm for frequent item set mining and association rule learning over relational databases. 

- It proceeds by identifying the frequent individual items in the database and extending them to larger and larger item sets as long as those item sets appear sufficiently often in the database. 

- The frequent item sets determined by Apriori can be used to determine association rules which highlight general trends in the database: this has applications in domains such as market basket analysis.

## Association rule learning


- Association rule learning is a rule-based machine learning method for discovering interesting relations between variables in large databases. 

- It is intended to identify strong rules discovered in databases using some measures of interestingness.

- In any given transaction with a variety of items, association rules are meant to discover the rules that determine how or why certain items are connected.

- Based on the concept of strong rules, Rakesh Agrawal, Tomasz Imieliński and Arun Swami introduced association rules for discovering regularities between products in large-scale transaction data recorded by point-of-sale (POS) systems in supermarkets. 

- For example, the rule {onions,potatoes}⇒{burger} found in the sales data of a supermarket would indicate that if a customer buys onions and potatoes together, they are likely to also buy hamburger meat. Such information can be used as the basis for decisions about marketing activities such as, e.g., promotional pricing or product placements.

- In addition to the above example from market basket analysis association rules are employed today in many application areas including Web usage mining, intrusion detection, continuous production, and bioinformatics.
-  In contrast with sequence mining, association rule learning typically does not consider the order of items either within a transaction or across transactions.

- The association rule algorithm itself consists of various parameters that can make it difficult for those without some expertise in data mining to execute, with many rules that are arduous to understand.

min_support : - Hyperparamter in Apriori:


    Apply the Apriori algorithm with minimum support of 30% and 
    minimum confidence of 70%, and 
    find all the association rules in the data set

    Consider the following transaction database.
    TID	Items
    01	A,B,C,D
    02	A,B,C,D,E,G
    03	A,C,G,H,K
    04	B,C,D,E,K
    05	D,E,F,H,L
    06	A,B,C,D,L
    07	B,I,E,K,L
    08	A,B,D,E,K
    09	A,E,F,H,L
    10	B,C,D,F


    Step 1: Scan D for count of each candidate. The candidate list is { A,B,C,D,E,F,G,H,I,K,L}

    C1=

    I=Itemsets	Support count
    A	6
    B	7
    C	6
    D	7
    E	6
    F	3
    G	2
    H	3
    I	1
    K	4
    L	4


    Step 2: Compare candidate support count with minimum support count (i.e.3)

    L1=

    I=Itemsets	Support count
    A	6
    B	7
    C	6
    D	7
    E	6
    F	3
    H	3
    K	4
    L	4


    Step 3: Generate candidate C2 from L1 and find the support.

    C2=

    I=Itemsets	Support count
    A,B	4
    A,C	4
    A,D	4
    A,E	3
    A,F	1
    A,H	2
    A,K	2
    A,L	1
    B,C	5
    B,D	5
    B,E	4
    B,F	1
    B,H	0
    B,K	3
    B,L	2
    C,D	5
    C,E	2
    C,F	1
    C,H	1
    C,K	2
    C,L	1
    D,E	4
    D,F	2
    D,H	1
    D,K	2
    D,L	2
    E,F	2
    E,H	2
    E,K	3
    E,L	3
    F,H	2
    F,K	0
    F,L	2
    H,K	1
    H,L	2
    K,L	1


    Step 4: Compare candidate (C2) support count with the minimum support count

    L2=

    I =Itemsets	Support count
    A,B	4
    A,C	4
    A,D	4
    A,E	3
    B,C	5
    B,D	5
    B,E	4
    B,K	3
    C,D	5
    D,E	4
    E,K	3
    E,L	3
    Step 5: Generate candidate C3 from L2 and find the support.

    C3=

    I =Itemsets	Support count
    A,B,C	3
    A,B,D	4
    A,B,E	2
    A,B,K	1
    A,C,D	3
    A,C,E	1
    A,D,E	2
    B,C,D	
    B,C,E	2
    B,C,K	1
    B,D,E	3
    B,D,K	2
    B,E,K	3
    C,E,D	2
    D,E,K	2
    D,E,L	1
    Step 6: Compare candidate (C3) support count with the minimum support count

    L3=

    I =Itemsets	Support count
    A,B,C	3
    A,B,D	4
    A,C,D	3
    B,C,D	5
    B,D,E	3
    B,E,K	3
    Step 7: Generate candidate C4 from L3 and find the support.

    C4=

    I =Itemsets	Support count
    A,B,C,D	3
    A,B,D,E	2
    B,C,D,E	2
    B,D,E,K	2
    Step 8: Compare candidate (C4) support count with the minimum support count

    L4=

    I =Itemsets	Support count
    A,B,C,D	3
    Step 9: So data contains the frequent itemsets: {A,B,C, D}

    Generate the Association rule from frequent itemsets with the support and confidence.

    Association Rule	Support	Confidence	Confidence %
    BCD => A	3	3/5	60%
    ACD =>B	3	3/3	100%
    ABD => C	3	3/4	75%
    ABC => D	3	3/3	100%
    CD =>AB	3	3/5	60%
    BD => AC	3	3/5	60%
    BC =>AD	3	3/5	60%
    AD =>BC	3	3/4	75%
    AC => BD	3	3/4	75%
    AB =>CD	3	3/4	75%
    D => ABC	3	3/7	43%
    C =>ABD	3	3/6	50%
    B =>ACD	3	3/7	43%
    A => BCD	3	3/6	50%
    Given minimum confidence threshold is 70%. So only ACD => B, ABD => C, ABC => D, AD =>BC, AC =>BD, AB =>CD rules are output.

    Final rules are:

    Rule 1: ACD => B

    Rule 2: ABD => C

    Rule 3: ABC => D

    Rule 4: AD =>BC

    Rule 5: AC =>BD

    Rule 6: AB =>CD

    ID    Items 

    1     Bread Milk
    2     Bread Diper Beer Egg
    3     Milk Diper Beer Coke
    4     Bread Milk Diper Beer
    5     Bread Milk Diper Coke   

    ItemSet     Support

    beer         3/5  = 0.6
    bread        4/5  = 0.8
    cola         2/5  = 0.4
    diper        4/5  = 0.8
    milk         4/5  = 0.8
    egg          1/5  = 0.2


    lets take min support = 0.5
    {beer,bread,diper,milk}

    for doubles:

        for milk -  milk bread   3   3/5 = 0.6
                    milk diper   3   3/5 = 0.6
                    milk beer    1   1/5 = 0.2



- When using Association rules, you are most likely to only use Support and Confidence. 
- However, this means you have to satisfy a user-specified minimum support and a user-specified minimum confidence at the same time. 
- Usually, the Association rule generation is split into two different steps that needs to be applied:

  - A minimum Support threshold to find all the frequent itemsets that are in the database.
  - A minimum Confidence threshold to the frequent itemsets found to create rules.

      To illustrate the concepts, we use a small example from the supermarket domain.

    transaction ID	milk	bread	butter	beer	diapers	eggs	fruit
              1      1      	1   	0    	 0    	0    	0    	1
              2      0      	0   	1         0    	0    	1    	1
              3      0      	0       0    	 1    	1    	0    	0
              4      1      	1   	1         0    	0    	1    	1
              5	  0      	1	   0	     0	    0	    0	    0

- shows a small database containing the items where, in each entry, the value 1 means the presence of the item in the corresponding transaction, and the value 0 represents the absence of an item in that transaction. The set of items is 
      - I={milk,bread,butter,beer,diapers,eggs,fruit}

- An example rule for the supermarket could be 
{butter,bread}⇒{milk} meaning that if butter and bread are bought, customers also buy milk.

- In order to select interesting rules from the set of all possible rules, constraints on various measures of significance and interest are used. The best-known constraints are minimum thresholds on support and confidence.

- Let X,Y be itemsets, X⇒Y an association rule and T a set of transactions of a given database.

- Note: this example is extremely small. In practical applications, a rule needs a support of several hundred transactions before it can be considered statistically significant, and datasets often contain thousands or millions of transactions.

## *Support*

- Support is an indication of how frequently the itemset appears in the dataset.

- In our example, it can be easier to explain support by writing

                            number of transaction containing A and B both
      support P[A ∩ B] =   ----------------------------------------------
                                  total number of transactions 
                            
- where A and B are separate item sets that occur in at the same time in a transaction.


## *Confidence*
- Conditional Probability

- Confidence is the percentage of all transactions satisfying X that also satisfy Y.

      -conditional probability P(Y|X) = P[Y and X]
                                          / P[X]
                                    = support(X and Y)
                                      / support(X)

- Overall, using confidence in association rule mining is great way to bring awareness to data relations. Its greatest benefit is highlighting the relationship between particular items to one another within the set, as it compares co-occurrences of items to the total occurrence of the antecedent in the specific rule.

- However, confidence is not the optimal method for every concept in association rule mining.

- The disadvantage of using it is that it does not offer multiple difference outlooks on the associations. 
- Unlike support, for instance, confidence does not provide the perspective of relationships between certain items in comparison to the entire dataset, so while milk and bread, for example, may occur 100% of the time for confidence,
 it only has a support of 0.4 (40%). This is why it is important to look at other viewpoints, such as Support x Confidence, instead of solely relying on one concept incessantly to define the relationships.



## *Lift*


    Lift X | Y  =    support (X and Y) / 
                  -----------------------
                    support(X) * support(Y)

- or the ratio of the observed support to that expected if X and Y were independent.

- For example, the rule {milk,bread}⇒{butter}  
   has a lift of 0.2 / 0.4 × 0.4 = 1.25


- If the rule had a lift of 1, it would imply that the probability of occurrence of the antecedent and that of the consequent are independent of each other. 
- When two events are independent of each other, no rule can be drawn involving those two events.

- If the lift is > 1, that lets us know the degree to which those two occurrences are dependent on one another, and makes those rules potentially useful for predicting the consequent in future data sets.

- If the lift is < 1, that lets us know the items are substitute to each other. This means that presence of one item has negative effect on presence of other item and vice versa.

- The value of lift is that it considers both the support of the rule and the overall data set.

https://en.wikipedia.org/wiki/Association_rule_learning

In [2]:
import warnings
warnings.filterwarnings("ignore")

In [3]:
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt

In [4]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
df = pd.read_csv("/content/drive/Othercomputers/My Laptop/Data Science Studies/GitHub_Desktop/DSML ML2_Unsupervised Learning/ML2_Unsupervised-Learning/online_retail_II.csv")
df.rename(columns = {'Invoice': 'InvoiceNo', 'Customer ID': 'CustomerID', 'Price': 'UnitPrice'}, inplace=True)
df.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009-12-01 07:45:00,6.95,13085.0,United Kingdom
1,489434,79323P,PINK CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
2,489434,79323W,WHITE CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2009-12-01 07:45:00,2.10,13085.0,United Kingdom
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009-12-01 07:45:00,1.25,13085.0,United Kingdom

In [ ]:
df.shape

(1067371, 8)

In [ ]:
df.sample(20)

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
103004,499237,22303,COFFEE MUG APPLES DESIGN,6,2010-02-25 13:19:00,2.55,13735.0,United Kingdom
414304,528954,22749,FELTCRAFT PRINCESS CHARLOTTE DOLL,4,2010-10-26 08:11:00,3.75,14156.0,EIRE
26513,491662,22147,FELTCRAFT BUTTERFLY HEARTS,2,2009-12-13 11:16:00,1.45,15169.0,United Kingdom
181917,506689,84782B,BLACK 3 TIER GLASS PLATE STAND,1,2010-05-02 11:56:00,12.75,15046.0,United Kingdom
968040,574677,21094,SET/6 RED SPOTTY PAPER PLATES,3,2011-11-06 12:32:00,0.85,16445.0,United Kingdom
689291,550627,84970S,HANGING HEART ZINC T-LIGHT HOLDER,12,2011-04-19 14:36:00,0.85,16633.0,United Kingdom
732882,554989,16235,RECYCLED PENCIL WITH RABBIT ERASER,36,2011-05-29 13:50:00,0.21,15897.0,United Kingdom
961210,574076,22963,JAM JAR WITH GREEN LID,1,2011-11-02 15:38:00,1.63,NaN,United Kingdom
77795,496487,85114B,IVORY ENCHANTED FOREST PLACEMAT,1,2010-02-01 17:13:00,3.36,NaN,United Kingdom
598388,C542273,20980,36 PENCILS TUBE POSY,-9,2011-01-27 10:01:00,1.25,12578.0,Italy
473818,534006,84380,SET OF 3 BUTTERFLY COOKIE CUTTERS,4,2010-11-19 14:29:00,3.36,NaN,United Kingdom
270825,515621,82482,WOODEN PICTURE FRAME WHITE FINISH,72,2010-07-14 09:54:00,2.10,14258.0,United Kingdom
700909,551960,21116,OWL DOORSTOP,3,2011-05-05 12:38:00,4.95,18239.0,United Kingdom
248619,513422,21080,SET/20 RED SPOTTY PAPER NAPKINS,1,2010-06-24 12:49:00,0.85,14527.0,United Kingdom
576132,540551,85049H,URBAN BLACK RIBBONS,8,2011-01-10 09:43:00,0.85,NaN,United Kingdom
197412,508333,84684,BEACH HUT PHOTO FRAME,96,2010-05-14 12:00:00,0.85,13694.0,United Kingdom
1033753,579196,22931,BAKING MOULD HEART WHITE CHOCOLATE,1,2011-11-28 15:54:00,4.96,14096.0,United Kingdom
489453,535269,22952,60 CAKE CASES VINTAGE CHRISTMAS,2,2010-11-25 13:38:00,0.55,14597.0,United Kingdom
4568,489822,22097,SWALLOW SQUARE TISSUE BOX,4,2009-12-02 13:26:00,1.25,14204.0,United Kingdom
1044785,580140,22424,ENAMEL BREAD BIN CREAM,1,2011-12-02 09:19:00,12.75,14895.0,United Kingdom

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1067371 entries, 0 to 1067370
Data columns (total 8 columns):
 #   Column       Non-Null Count    Dtype
---  ------       --------------    -----
 0   InvoiceNo    1067371 non-null  object
 1   StockCode    1067371 non-null  object
 2   Description  1062989 non-null  object
 3   Quantity     1067371 non-null  int64
 4   InvoiceDate  1067371 non-null  object
 5   UnitPrice    1067371 non-null  float64
 6   CustomerID   824364 non-null   float64
 7   Country      1067371 non-null  object
dtypes: float64(2), int64(1), object(5)
memory usage: 65.1+ MB

In [ ]:
(df.isna().sum() / len(df)) *100

InvoiceNo       0.000000
StockCode       0.000000
Description     0.410541
Quantity        0.000000
InvoiceDate     0.000000
UnitPrice       0.000000
CustomerID     22.766873
Country         0.000000
dtype: float64

In [ ]:
df["InvoiceNo"].nunique()

53628

In [ ]:
df["CustomerID"].nunique()

5942

In [ ]:

df["StockCode"].nunique()  # Unique products

5305

In [ ]:
df.describe()

           Quantity     UnitPrice     CustomerID
count  1.067371e+06  1.067371e+06  824364.000000
mean   9.938898e+00  4.649388e+00   15324.638504
std    1.727058e+02  1.235531e+02    1697.464450
min   -8.099500e+04 -5.359436e+04   12346.000000
25%    1.000000e+00  1.250000e+00   13975.000000
50%    3.000000e+00  2.100000e+00   15255.000000
75%    1.000000e+01  4.150000e+00   16797.000000
max    8.099500e+04  3.897000e+04   18287.000000

In [ ]:
len(df[df["Quantity"] < 0])
# Returend Orders

22950

In [ ]:
len(df[df["Quantity"] < 0]) / len(df) * 100
# 2.15% return orders

2.1501427338760375

In [ ]:
df = df[df['Quantity']>=0]
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1044421 entries, 0 to 1067370
Data columns (total 8 columns):
 #   Column       Non-Null Count    Dtype
---  ------       --------------    -----
 0   InvoiceNo    1044421 non-null  object
 1   StockCode    1044421 non-null  object
 2   Description  1042728 non-null  object
 3   Quantity     1044421 non-null  int64
 4   InvoiceDate  1044421 non-null  object
 5   UnitPrice    1044421 non-null  float64
 6   CustomerID   805620 non-null   float64
 7   Country      1044421 non-null  object
dtypes: float64(2), int64(1), object(5)
memory usage: 71.7+ MB

In [ ]:
len(df)

1044421

In [ ]:
len(df.dropna(axis=0, subset=['InvoiceNo']))

1044421

In [ ]:
df.dropna(axis=0, subset=['InvoiceNo'],inplace=True)

In [ ]:
df['InvoiceNo']=df['InvoiceNo'].astype('str')
# Converting InvoiceNo to String

In [ ]:
# df["InvoiceNo"].sample(20)

In [ ]:
df[df['InvoiceNo'].str.contains('C')]

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
76799,C496350,M,Manual,1,2010-02-01 08:24:00,373.57,NaN,United Kingdom

In [ ]:
df[df['InvoiceNo'].str.contains('A')]

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
179403,A506401,B,Adjust bad debt,1,2010-04-29 13:36:00,-53594.36,NaN,United Kingdom
276274,A516228,B,Adjust bad debt,1,2010-07-19 11:24:00,-44031.79,NaN,United Kingdom
403472,A528059,B,Adjust bad debt,1,2010-10-20 12:04:00,-38925.87,NaN,United Kingdom
825443,A563185,B,Adjust bad debt,1,2011-08-12 14:50:00,11062.06,NaN,United Kingdom
825444,A563186,B,Adjust bad debt,1,2011-08-12 14:51:00,-11062.06,NaN,United Kingdom
825445,A563187,B,Adjust bad debt,1,2011-08-12 14:52:00,-11062.06,NaN,United Kingdom

In [ ]:
len(df)

1044421

In [ ]:
df = df[~df['InvoiceNo'].str.contains('C')]
df = df[~df['InvoiceNo'].str.contains('A')]
df.shape

(1044414, 8)

In [ ]:
df.shape

(1044414, 8)

In [ ]:
df['Country'].value_counts()

United Kingdom          961217
EIRE                     17354
Germany                  16703
France                   13941
Netherlands               5093
Spain                     3720
Switzerland               3137
Belgium                   3069
Portugal                  2562
Australia                 1815
Channel Islands           1569
Italy                     1468
Norway                    1437
Sweden                    1338
Cyprus                    1155
Finland                   1032
Austria                    922
Denmark                    798
Unspecified                752
Greece                     657
Poland                     512
Japan                      485
United Arab Emirates       467
USA                        409
Israel                     369
Hong Kong                  358
Singapore                  339
Malta                      282
Iceland                    253
Canada                     228
Lithuania                  189
RSA                        168
Bahrain                    124
Brazil                      94
Thailand                    76
European Community          60
Lebanon                     57
West Indies                 54
Korea                       53
Bermuda                     34
Nigeria                     30
Czech Republic              25
Saudi Arabia                 9
Name: Country, dtype: int64

In [ ]:
# Filtering data for United Kingdom 
# grouping by InvoiceNo and Description 
# summing up the Quantity and Unstacking the data . 
# each product will have either Quantity or 0 as result

In [ ]:
df[df['Country'] =="United Kingdom"].groupby(['InvoiceNo', 'Description'])['Quantity'].sum()

InvoiceNo  Description
489434      WHITE CHERRY LIGHTS                   12
           15CM CHRISTMAS GLASS BALL 20 LIGHTS    12
           FANCY FONT HOME SWEET HOME DOORMAT     10
           PINK CHERRY LIGHTS                     12
           PINK DOUGHNUT TRINKET POT              24
                                                  ..
581585     ZINC WILLIE WINKIE  CANDLE STICK       24
581586     DOORMAT RED RETROSPOT                  10
           LARGE CAKE STAND  HANGING STRAWBERY     8
           RED RETROSPOT ROUND CAKE TINS          24
           SET OF 3 HANGING OWLS OLLIE BEAK       24
Name: Quantity, Length: 915314, dtype: int64

In [ ]:
df[df['Country'] =="United Kingdom"].groupby(['InvoiceNo', 'Description'])['Quantity'].sum().unstack().reset_index().fillna(0).set_index('InvoiceNo').sample(10)

Description,DOORMAT UNION JACK GUNS AND ROSES,3 STRIPEY MICE FELTCRAFT,4 PURPLE FLOCK DINNER CANDLES,50'S CHRISTMAS GIFT BAG LARGE,ANIMAL STICKERS,BLACK PIRATE TREASURE CHEST,BROWN PIRATE TREASURE CHEST,Bank Charges,CAMPHOR WOOD PORTOBELLO MUSHROOM,CHERRY BLOSSOM DECORATIVE FLASK,...,tk maxx mix up with pink,to push order througha s stock was,update,website fixed,wrong invc,wrongly coded 20713,wrongly coded 23343,wrongly marked,wrongly marked 23343,wrongly sold (22719) barcode
InvoiceNo,,,,,,,,,,,,,,,,,,,,,
544408,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
535815,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
574672,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
579759,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
568390,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
528086,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
570011,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
534056,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
509041,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
496476,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [ ]:
data = (df[df['Country'] =="United Kingdom"].groupby(['InvoiceNo', 'Description'])['Quantity']
               .sum().unstack().reset_index().fillna(0).set_index('InvoiceNo'))

In [ ]:
data.sample(15)

Description,DOORMAT UNION JACK GUNS AND ROSES,3 STRIPEY MICE FELTCRAFT,4 PURPLE FLOCK DINNER CANDLES,50'S CHRISTMAS GIFT BAG LARGE,ANIMAL STICKERS,BLACK PIRATE TREASURE CHEST,BROWN PIRATE TREASURE CHEST,Bank Charges,CAMPHOR WOOD PORTOBELLO MUSHROOM,CHERRY BLOSSOM DECORATIVE FLASK,...,tk maxx mix up with pink,to push order througha s stock was,update,website fixed,wrong invc,wrongly coded 20713,wrongly coded 23343,wrongly marked,wrongly marked 23343,wrongly sold (22719) barcode
InvoiceNo,,,,,,,,,,,,,,,,,,,,,
565408,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
523664,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
495898,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
544088,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
554347,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
546899,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
490958,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
493052,0.0,6.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
563161,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
549579,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
506393,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
505530,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
556248,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
503143,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
501316,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [ ]:
len(data)

36752

In [ ]:
data.shape

(36752, 5438)

In [ ]:
# 36752 Invoices , and 5438 products

In [ ]:
data.sum(axis=1).sample(5)

InvoiceNo
552267     21.0
564090    349.0
566311     78.0
543589    200.0
515329    498.0
dtype: float64

In [ ]:
# where the Quantity sold more than 1 , mark it as 1 or else keep it 0 .

In [ ]:
(data > 0).astype(int)

Description,DOORMAT UNION JACK GUNS AND ROSES,3 STRIPEY MICE FELTCRAFT,4 PURPLE FLOCK DINNER CANDLES,50'S CHRISTMAS GIFT BAG LARGE,ANIMAL STICKERS,BLACK PIRATE TREASURE CHEST,BROWN PIRATE TREASURE CHEST,Bank Charges,CAMPHOR WOOD PORTOBELLO MUSHROOM,CHERRY BLOSSOM DECORATIVE FLASK,...,tk maxx mix up with pink,to push order througha s stock was,update,website fixed,wrong invc,wrongly coded 20713,wrongly coded 23343,wrongly marked,wrongly marked 23343,wrongly sold (22719) barcode
InvoiceNo,,,,,,,,,,,,,,,,,,,,,
489434,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
489435,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
489436,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
489437,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
489438,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
581582,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
581583,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
581584,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
581585,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
581586,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [ ]:
data = (data > 0).astype(int)
data

Description,DOORMAT UNION JACK GUNS AND ROSES,3 STRIPEY MICE FELTCRAFT,4 PURPLE FLOCK DINNER CANDLES,50'S CHRISTMAS GIFT BAG LARGE,ANIMAL STICKERS,BLACK PIRATE TREASURE CHEST,BROWN PIRATE TREASURE CHEST,Bank Charges,CAMPHOR WOOD PORTOBELLO MUSHROOM,CHERRY BLOSSOM DECORATIVE FLASK,...,tk maxx mix up with pink,to push order througha s stock was,update,website fixed,wrong invc,wrongly coded 20713,wrongly coded 23343,wrongly marked,wrongly marked 23343,wrongly sold (22719) barcode
InvoiceNo,,,,,,,,,,,,,,,,,,,,,
489434,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
489435,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
489436,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
489437,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
489438,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
581582,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
581583,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
581584,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
581585,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
581586,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [ ]:
data.shape

(36752, 5438)

In [ ]:
data.sum(axis=1).sample(5)

InvoiceNo
514209     8
516720    24
539721     1
518556    29
558703    22
dtype: int64

In [ ]:
# Now we see,  per invoice, how many unique products were sold .

In [ ]:
from mlxtend.frequent_patterns import apriori

In [ ]:
frequent_itemsets_plus = apriori(data, min_support=0.015, 
                                 use_colnames=True).sort_values('support', ascending=False).reset_index(drop=True)

In [ ]:
frequent_itemsets_plus['length'] = frequent_itemsets_plus['itemsets'].apply(lambda x: len(x))

frequent_itemsets_plus

      support                              itemsets  length
0    0.143013  (WHITE HANGING HEART T-LIGHT HOLDER)       1
1    0.093628            (REGENCY CAKESTAND 3 TIER)       1
2    0.082989             (JUMBO BAG RED RETROSPOT)       1
3    0.072051       (ASSORTED COLOUR BIRD ORNAMENT)       1
4    0.069003                       (PARTY BUNTING)       1
..        ...                                   ...     ...
481  0.015074         (12 PENCILS TALL TUBE SKULLS)       1
482  0.015047             (BLACK HEART CARD HOLDER)       1
483  0.015020                 (ROBOT BIRTHDAY CARD)       1
484  0.015020          (FLORAL FOLK STATIONERY SET)       1
485  0.015020         (LARGE WHITE HEART OF WICKER)       1

[486 rows x 3 columns]

In [ ]:
frequent_itemsets_plus.loc[frequent_itemsets_plus.length==2]

      support                                           itemsets  length
72   0.031971  (RED HANGING HEART T-LIGHT HOLDER, WHITE HANGI...       2
90   0.029658  (WOODEN FRAME ANTIQUE WHITE , WOODEN PICTURE F...       2
99   0.028788  (JUMBO STORAGE BAG SUKI, JUMBO BAG RED RETROSPOT)       2
121  0.026965  (STRAWBERRY CERAMIC TRINKET BOX, SWEETHEART CE...       2
123  0.026937     (HEART OF WICKER SMALL, HEART OF WICKER LARGE)       2
..        ...                                                ...     ...
464  0.015482  (CREAM HEART CARD HOLDER, WHITE HANGING HEART ...       2
470  0.015373  (LUNCH BAG  BLACK SKULL., WHITE HANGING HEART ...       2
472  0.015346           (DOTCOM POSTAGE, JUMBO STORAGE BAG SUKI)       2
473  0.015319  (JUMBO BAG STRAWBERRY, JUMBO SHOPPER VINTAGE R...       2
475  0.015292  (JUMBO BAG RED RETROSPOT, LUNCH BAG  BLACK SKU...       2

[93 rows x 3 columns]

In [ ]:
frequent_itemsets_plus.loc[frequent_itemsets_plus.length==2].shape

(93, 3)

In [ ]:
frequent_itemsets_plus.loc[frequent_itemsets_plus.length==3]

      support                                           itemsets  length
341  0.018013  (ROSES REGENCY TEACUP AND SAUCER , GREEN REGEN...       3

In [ ]:
from mlxtend.frequent_patterns import association_rules
rules = association_rules(frequent_itemsets_plus, metric ="lift", min_threshold = 1)
rules.head()

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction
0,(RED HANGING HEART T-LIGHT HOLDER),(WHITE HANGING HEART T-LIGHT HOLDER),0.045521,0.143013,0.031971,0.702331,4.910973,0.025461,2.878996
1,(WHITE HANGING HEART T-LIGHT HOLDER),(RED HANGING HEART T-LIGHT HOLDER),0.143013,0.045521,0.031971,0.223554,4.910973,0.025461,1.229292
2,(WOODEN FRAME ANTIQUE WHITE ),(WOODEN PICTURE FRAME WHITE FINISH),0.054419,0.053167,0.029658,0.545000,10.250686,0.026765,2.080951
3,(WOODEN PICTURE FRAME WHITE FINISH),(WOODEN FRAME ANTIQUE WHITE ),0.053167,0.054419,0.029658,0.557830,10.250686,0.026765,2.138502
4,(JUMBO STORAGE BAG SUKI),(JUMBO BAG RED RETROSPOT),0.060650,0.082989,0.028788,0.474652,5.719483,0.023754,1.745532

In [ ]:
rules.loc[rules.antecedents == rules.antecedents.iloc[5]].sort_values('lift', ascending =False)

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction
14,(JUMBO BAG RED RETROSPOT),(JUMBO BAG PINK POLKADOT),0.082989,0.037413,0.025033,0.301639,8.062436,0.021928,1.378352
127,(JUMBO BAG RED RETROSPOT),(JUMBO BAG WOODLAND ANIMALS),0.082989,0.032706,0.016979,0.204590,6.255489,0.014264,1.216095
173,(JUMBO BAG RED RETROSPOT),(JUMBO BAG SPACEBOY DESIGN),0.082989,0.030828,0.015700,0.189180,6.136589,0.013141,1.195299
16,(JUMBO BAG RED RETROSPOT),(JUMBO BAG STRAWBERRY),0.082989,0.048623,0.024488,0.295082,6.068748,0.020453,1.349628
19,(JUMBO BAG RED RETROSPOT),(JUMBO BAG BAROQUE BLACK WHITE),0.082989,0.049848,0.024271,0.292459,5.867060,0.020134,1.342894
134,(JUMBO BAG RED RETROSPOT),(JUMBO STORAGE BAG SKULLS),0.082989,0.034937,0.016598,0.200000,5.724611,0.013698,1.206329
5,(JUMBO BAG RED RETROSPOT),(JUMBO STORAGE BAG SUKI),0.082989,0.060650,0.028788,0.346885,5.719483,0.023754,1.438262
66,(JUMBO BAG RED RETROSPOT),(JUMBO BAG PINK VINTAGE PAISLEY),0.082989,0.041304,0.019536,0.235410,5.699461,0.016109,1.253869
156,(JUMBO BAG RED RETROSPOT),(JUMBO BAG OWLS),0.082989,0.033767,0.015945,0.192131,5.689931,0.013142,1.196027
10,(JUMBO BAG RED RETROSPOT),(JUMBO SHOPPER VINTAGE RED PAISLEY),0.082989,0.057357,0.026529,0.319672,5.573335,0.021769,1.385571
121,(JUMBO BAG RED RETROSPOT),(DOTCOM POSTAGE),0.082989,0.038637,0.017196,0.207213,5.363026,0.013990,1.212637
145,(JUMBO BAG RED RETROSPOT),(RECYCLING BAG RETROSPOT ),0.082989,0.040215,0.016326,0.196721,4.891679,0.012988,1.194834
107,(JUMBO BAG RED RETROSPOT),(LUNCH BAG RED RETROSPOT),0.082989,0.044868,0.017468,0.210492,4.691325,0.013745,1.209781
190,(JUMBO BAG RED RETROSPOT),(LUNCH BAG BLACK SKULL.),0.082989,0.061276,0.015292,0.184262,3.007108,0.010207,1.150767
74,(JUMBO BAG RED RETROSPOT),(WHITE HANGING HEART T-LIGHT HOLDER),0.082989,0.143013,0.019291,0.232459,1.625444,0.007423,1.116536

# Content Based Recommender System

In [ ]:
import numpy as np
import pandas as pd
from datetime import datetime
import warnings
warnings.filterwarnings('ignore')

In [ ]:
movies = pd.read_csv('/content/drive/Othercomputers/My Laptop/Data Science Studies/GitHub_Desktop/DSML ML2_Unsupervised Learning/ML2_Unsupervised-Learning/movies.csv')
ratings = pd.read_csv('/content/drive/Othercomputers/My Laptop/Data Science Studies/GitHub_Desktop/DSML ML2_Unsupervised Learning/ML2_Unsupervised-Learning/ratings.csv')
users = pd.read_csv('/content/drive/Othercomputers/My Laptop/Data Science Studies/GitHub_Desktop/DSML ML2_Unsupervised Learning/ML2_Unsupervised-Learning/users.csv')

In [ ]:
movies.shape,ratings.shape,users.shape

((10329, 3), (105339, 4), (668, 3))

In [ ]:
movies.sample(5)

,movieId,title,genres
3032,3837,Phantasm II (1988),Action|Fantasy|Horror|Sci-Fi|Thriller
3198,4054,Save the Last Dance (2001),Drama|Romance
8621,78905,Whirlpool (1949),Crime|Drama|Film-Noir|Mystery
4977,6819,"Rage in Harlem, A (1991)",Crime
4259,5582,Captain Ron (1992),Adventure|Comedy

In [ ]:
ratings.head(5)

   userId  movieId  rating   timestamp
0       1       16     4.0  1217897793
1       1       24     1.5  1217895807
2       1       32     4.0  1217896246
3       1       47     4.0  1217896556
4       1       50     4.0  1217896523

In [ ]:
users.sample(5)

     userId  age  time_spent_per_day
119     120   22            4.614820
298     299   23            4.630642
592     593   24            2.003256
20       21   33            1.208271
474     475   18            5.782397

In [ ]:
## Item-Item similarity based recommendation 
## you may also like : Recommendation 
## Movie recommendation as per genere
movies.sample(5)

      movieId                                title                  genres
2751     3466               Heart and Souls (1993)          Comedy|Fantasy
6810    40278                       Jarhead (2005)        Action|Drama|War
8716    80763       Saint John of Las Vegas (2009)            Comedy|Drama
8601    78528          East Side, West Side (1949)     Crime|Drama|Romance
827      1019  20,000 Leagues Under the Sea (1954)  Adventure|Drama|Sci-Fi

In [ ]:

# ratings["movieId"].value_counts().head(1000).index.to_list()

# finding top 1000 , most rated movies, so  that we have more data

In [ ]:
selected_movies = ratings["movieId"].value_counts().head(1000).index.to_list()

In [ ]:
movies = movies.loc[movies["movieId"].isin(selected_movies)]
ratings = ratings.loc[ratings["movieId"].isin(selected_movies)]

In [ ]:
movies.shape,ratings.shape

((1000, 3), (63250, 4))

In [ ]:
m = movies.copy()

In [ ]:
m.sample()

      movieId          title                         genres
1091     1345  Carrie (1976)  Drama|Fantasy|Horror|Thriller

In [ ]:
m["genres"] = m["genres"].str.split("|")

In [ ]:
m.sample()

     movieId                   title              genres
335      376  River Wild, The (1994)  [Action, Thriller]

In [ ]:
m = m.explode("genres").pivot(index = "movieId",
                         columns="genres",
                         values="title")

In [ ]:
m.sample()

genres,Action,Adventure,Animation,Children,Comedy,Crime,Documentary,Drama,Fantasy,Film-Noir,Horror,IMAX,Musical,Mystery,Romance,Sci-Fi,Thriller,War,Western
movieId,,,,,,,,,,,,,,,,,,,
2078,NaN,NaN,"Jungle Book, The (1967)","Jungle Book, The (1967)","Jungle Book, The (1967)",NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Jungle Book, The (1967)",NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
m = ~m.isna()

In [ ]:
m=  m.astype(int)

In [ ]:
m.head(2)

genres,Action,Adventure,Animation,Children,Comedy,Crime,Documentary,Drama,Fantasy,Film-Noir,Horror,IMAX,Musical,Mystery,Romance,Sci-Fi,Thriller,War,Western
movieId,,,,,,,,,,,,,,,,,,,
1,0,1,1,1,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0
2,0,1,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0

In [ ]:
m.shape # hamming distance will work best to find similarity

(1000, 19)

In [ ]:
# Hamming distance 
q1 = m.iloc[100].values
q2 = m.iloc[101].values

def hamming_distance(q1,q2):
    return np.sum(abs(q1-q2))

print(q1)
print(q2)

print(hamming_distance(q1,q2))

q1 = m.iloc[10].values
q2 = m.iloc[11].values

print(q1)
print(q2)

print(hamming_distance(q1,q2))

[1 0 0 0 1 0 0 0 0 0 0 0 0 0 0 1 0 0 0]
[0 1 0 0 0 0 0 1 0 0 0 0 0 0 0 1 0 0 0]
4
[0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 1 0 0]
2

In [ ]:
ranks = []

for query in m.index[:50]:
    for candidate in m.index:
        if candidate == query:
            continue
        ranks.append([query, candidate, hamming_distance(m.loc[query], m.loc[candidate])])

In [ ]:
ranks = pd.DataFrame(ranks,columns=["query","candidate","hamming_distance"])
ranks.head(3)

   query  candidate  hamming_distance
0      1          2                 2
1      1          3                 5
2      1          5                 4

In [ ]:

ranks = ranks.merge(movies[['movieId', 'title']], left_on='query', right_on='movieId').rename(columns={'title': 'query_tittle'}).drop(columns=['movieId'])
ranks = ranks.merge(movies[['movieId', 'title']], left_on='candidate', right_on='movieId').rename(columns={'title': 'candidate_tittle'}).drop(columns=['movieId'])
ranks = ranks.sort_values(by=['query', 'hamming_distance'])
ranks.head()

,query,candidate,hamming_distance,query_tittle,candidate_tittle
26951,1,2294,0,Toy Story (1995),Antz (1998)
33251,1,3114,0,Toy Story (1995),Toy Story 2 (1999)
39601,1,4886,0,Toy Story (1995),"Monsters, Inc. (2001)"
9351,1,673,1,Toy Story (1995),Space Jam (1996)
27451,1,2355,1,Toy Story (1995),"Bug's Life, A (1998)"

In [ ]:
ranks["query_tittle"].unique()

array(['Toy Story (1995)', 'Jumanji (1995)', 'Grumpier Old Men (1995)',
       'Father of the Bride Part II (1995)', 'Heat (1995)',
       'Sabrina (1995)', 'GoldenEye (1995)',
       'American President, The (1995)', 'Casino (1995)',
       'Sense and Sensibility (1995)',
       'Ace Ventura: When Nature Calls (1995)', 'Get Shorty (1995)',
       'Copycat (1995)', 'Powder (1995)', 'Leaving Las Vegas (1995)',
       'City of Lost Children, The (Cité des enfants perdus, La) (1995)',
       'Dangerous Minds (1995)',
       'Twelve Monkeys (a.k.a. 12 Monkeys) (1995)', 'Babe (1995)',
       'Dead Man Walking (1995)', 'Clueless (1995)',
       'Mortal Kombat (1995)', 'To Die For (1995)',
       'Seven (a.k.a. Se7en) (1995)', 'Pocahontas (1995)',
       'Usual Suspects, The (1995)', 'Mighty Aphrodite (1995)',
       'Postman, The (Postino, Il) (1994)', "Mr. Holland's Opus (1995)",
       'Bio-Dome (1996)', 'From Dusk Till Dawn (1996)',
       'Black Sheep (1996)', 'Broken Arrow (1996)',
       'Happy Gilmore (1996)', 'Bridges of Madison County, The (1995)',
       'Muppet Treasure Island (1996)', 'Braveheart (1995)',
       'Taxi Driver (1976)', 'Rumble in the Bronx (Hont faan kui) (1995)',
       'Down Periscope (1996)', 'Birdcage, The (1996)', 'Bad Boys (1995)',
       'Apollo 13 (1995)', 'Rob Roy (1995)', 'Batman Forever (1995)',
       'Casper (1995)', 'Congo (1995)', 'Crimson Tide (1995)',
       'Desperado (1995)', 'Die Hard: With a Vengeance (1995)'],
      dtype=object)

In [ ]:
# top 5 similarity based recommendation , for Query of Jumanji1995 
ranks.loc[ranks["query_tittle"] == "Jumanji (1995)"].head(5)

,query,candidate,hamming_distance,query_tittle,candidate_tittle
26152,2,2161,0,Jumanji (1995),"NeverEnding Story, The (1984)"
39652,2,4896,0,Jumanji (1995),Harry Potter and the Sorcerer's Stone (a.k.a. ...
45602,2,41566,0,Jumanji (1995),"Chronicles of Narnia: The Lion, the Witch and ..."
2157,2,158,1,Jumanji (1995),Casper (1995)
11502,2,919,1,Jumanji (1995),"Wizard of Oz, The (1939)"

In [ ]:

ranks.loc[ranks["query_tittle"] == "Batman Forever (1995)"].head(5)

,query,candidate,hamming_distance,query_tittle,candidate_tittle
1856,153,112,0,Batman Forever (1995),Rumble in the Bronx (Hont faan kui) (1995)
20095,153,1517,1,Batman Forever (1995),Austin Powers: International Man of Mystery (1...
29895,153,2683,1,Batman Forever (1995),Austin Powers: The Spy Who Shagged Me (1999)
37695,153,4027,1,Batman Forever (1995),"O Brother, Where Art Thou? (2000)"
2495,153,170,2,Batman Forever (1995),Hackers (1995)

# User User Similarity Based RecSystem

In [ ]:
users.head(5)

   userId  age  time_spent_per_day
0       1   16            3.976315
1       2   24            1.891303
2       3   20            4.521478
3       4   23            2.095284
4       5   35            1.759860

In [ ]:
r = ratings.copy()
r.head(5)

   userId  movieId  rating   timestamp
0       1       16     4.0  1217897793
1       1       24     1.5  1217895807
2       1       32     4.0  1217896246
3       1       47     4.0  1217896556
4       1       50     4.0  1217896523

In [ ]:
r["hour"] = r["timestamp"].apply(lambda x:datetime.fromtimestamp(x).hour)

In [ ]:
r.sample(5) # hour is the at what time used watched movie and rated the movie

       userId  movieId  rating   timestamp  hour
45585     321      261     4.0   848665822    12
79776     560     3608     4.0  1069092603    18
13435     111      153     5.0   847916505    20
41841     296     4963     3.5  1085799150     2
18477     145       50     5.0   955414627     0

In [ ]:
users = users.merge(r.groupby("userId")["rating"].mean().reset_index(),on="userId")
users = users.merge(r.groupby("userId")["hour"].mean().reset_index(),on="userId")

In [ ]:
users

     userId  age  time_spent_per_day    rating       hour
0         1   16            3.976315  3.691589   0.000000
1         2   24            1.891303  3.923077  16.000000
2         3   20            4.521478  3.806452   9.000000
3         4   23            2.095284  4.159420   2.057971
4         5   35            1.759860  2.864865  19.000000
..      ...  ...                 ...       ...        ...
663     664   22            5.288101  3.964286  16.000000
664     665   20            5.220446  3.553763  12.086022
665     666   19            3.262313  3.642857   8.111111
666     667   17            3.674356  3.807692  14.707692
667     668   24            2.718718  3.044785   9.733560

[668 rows x 5 columns]

In [ ]:
users.shape

(668, 5)

In [ ]:
u = users.copy()

In [ ]:
u = u.set_index('userId')

In [ ]:


u.columns = ['age', 'time_spent_per_day', 'u_avg_rating', 'hour']

In [ ]:
# u

In [ ]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
u = pd.DataFrame(scaler.fit_transform(u), columns=u.columns, index=u.index)

def euclidian_distance(x, y):
    return np.linalg.norm(x-y)

In [ ]:
userid = 1
dist = []
for user in u.index:
    dist.append(euclidian_distance(u.loc[userid], u.loc[user]))

u_rank = pd.DataFrame()
u_rank['id'] = u.index
u_rank['dist'] = dist
u_rank = u_rank.loc[u_rank.id != userid]
u_rank = u_rank.sort_values(by='dist')
u_rank.head() # top 5 similar users

      id      dist
185  186  0.822787
176  177  0.847579
489  490  0.847942
79    80  0.917464
461  462  0.995152

In [ ]:
pd.set_option('display.max_rows', 500)
pd.set_option('display.max_columns', 500)
pd.set_option('display.width', 10000)

# Regression based Recommender system

In [ ]:
m

genres   Action  Adventure  Animation  Children  Comedy  Crime  Documentary  Drama  Fantasy  Film-Noir  Horror  IMAX  Musical  Mystery  Romance  Sci-Fi  Thriller  War  Western
movieId
1             0          1          1         1       1      0            0      0        1          0       0     0        0        0        0       0         0    0        0
2             0          1          0         1       0      0            0      0        1          0       0     0        0        0        0       0         0    0        0
3             0          0          0         0       1      0            0      0        0          0       0     0        0        0        1       0         0    0        0
5             0          0          0         0       1      0            0      0        0          0       0     0        0        0        0       0         0    0        0
6             1          0          0         0       0      1            0      0        0          0       0     0        0        0        0       0         1    0        0
...         ...        ...        ...       ...     ...    ...          ...    ...      ...        ...     ...   ...      ...      ...      ...     ...       ...  ...      ...
109374        0          0          0         0       1      0            0      1        0          0       0     0        0        0        0       0         0    0        0
109487        0          0          0         0       0      0            0      0        0          0       0     1        0        0        0       1         0    0        0
111759        1          0          0         0       0      0            0      0        0          0       0     1        0        0        0       1         0    0        0
112852        1          1          0         0       0      0            0      0        0          0       0     0        0        0        0       1         0    0        0
116797        0          0          0         0       0      0            0      1        0          0       0     0        0        0        0       0         1    1        0

[1000 rows x 19 columns]

In [ ]:
u

             age  time_spent_per_day  u_avg_rating      hour
userId
1      -1.470292            0.341073     -0.073572 -1.900624
2      -0.135616           -1.079947      0.426461  0.610601
3      -0.802954            0.712624      0.174541 -0.488060
4      -0.302450           -0.940926      0.936982 -1.577622
5       1.699565           -1.169532     -1.859363  1.081456
...          ...                 ...           ...       ...
664    -0.469285            1.235109      0.515476  0.610601
665    -0.802954            1.188999     -0.371286 -0.003704
666    -0.969789           -0.145549     -0.178836 -0.627572
667    -1.303458            0.135276      0.177221  0.407771
668    -0.135616           -0.516031     -1.470722 -0.372926

[668 rows x 4 columns]

In [ ]:
r = ratings[["movieId","userId","rating"]].copy()

In [ ]:
r

        movieId  userId  rating
0            16       1     4.0
1            24       1     1.5
2            32       1     4.0
3            47       1     4.0
4            50       1     4.0
...         ...     ...     ...
105148   109374     668     4.0
105151   109487     668     4.0
105185   111759     668     3.0
105205   112852     668     4.0
105252   116797     668     4.0

[63250 rows x 3 columns]

In [ ]:
r.shape

(63250, 3)

In [ ]:
u = u.reset_index()
m = m.reset_index()

In [ ]:
u.columns,m.columns,r.columns

(Index(['userId', 'age', 'time_spent_per_day', 'u_avg_rating', 'hour'], dtype='object'),
 Index(['movieId', 'Action', 'Adventure', 'Animation', 'Children', 'Comedy', 'Crime', 'Documentary', 'Drama', 'Fantasy', 'Film-Noir', 'Horror', 'IMAX', 'Musical', 'Mystery', 'Romance', 'Sci-Fi', 'Thriller', 'War', 'Western'], dtype='object', name='genres'),
 Index(['movieId', 'userId', 'rating'], dtype='object'))

In [ ]:
X = r.merge(u,on="userId",how="right").merge(m,on="movieId",how="right")

In [ ]:
X.head(10)

   movieId  userId  rating       age  time_spent_per_day  u_avg_rating      hour  Action  Adventure  Animation  Children  Comedy  Crime  Documentary  Drama  Fantasy  Film-Noir  Horror  IMAX  Musical  Mystery  Romance  Sci-Fi  Thriller  War  Western
0        1       2     5.0 -0.135616           -1.079947      0.426461  0.610601       0          1          1         1       1      0            0      0        1          0       0     0        0        0        0       0         0    0        0
1        1       5     4.0  1.699565           -1.169532     -1.859363  1.081456       0          1          1         1       1      0            0      0        1          0       0     0        0        0        0       0         0    0        0
2        1       8     5.0  0.364888            0.298545      0.160605  0.453650       0          1          1         1       1      0            0      0        1          0       0     0        0        0        0       0         0    0        0
3        1      11     4.0 -1.303458            0.513712     -0.380602 -0.424244       0          1          1         1       1      0            0      0        1          0       0     0        0        0        0       0         0    0        0
4        1      14     4.0 -0.302450            1.251552     -0.379415 -0.488060       0          1          1         1       1      0            0      0        1          0       0     0        0        0        0       0         0    0        0
5        1      17     5.0  0.865392            0.600791      0.736627  0.387381       0          1          1         1       1      0            0      0        1          0       0     0        0        0        0       0         0    0        0
6        1      28     3.0  0.198054           -0.344992     -0.319827  0.419824       0          1          1         1       1      0            0      0        1          0       0     0        0        0        0       0         0    0        0
7        1      29     4.0  0.364888            0.765658     -0.830785 -0.016298       0          1          1         1       1      0            0      0        1          0       0     0        0        0        0       0         0    0        0
8        1      30     4.5  0.031219           -0.487987      0.669767  0.139747       0          1          1         1       1      0            0      0        1          0       0     0        0        0        0       0         0    0        0
9        1      31     4.0  0.531723           -0.238468      0.362826 -1.115866       0          1          1         1       1      0            0      0        1          0       0     0        0        0        0       0         0    0        0

In [ ]:
X.shape

(63250, 26)

In [ ]:
X = X.drop(columns=["movieId","userId"])
y = X["rating"]

In [ ]:
X.sample(5)

       rating       age  time_spent_per_day  u_avg_rating      hour  Action  Adventure  Animation  Children  Comedy  Crime  Documentary  Drama  Fantasy  Film-Noir  Horror  IMAX  Musical  Mystery  Romance  Sci-Fi  Thriller  War  Western
61167     4.0 -0.969789           -1.378457      0.207344 -1.198472       0          0          0         0       1      0            0      1        0          0       0     0        0        0        1       0         0    0        0
50399     4.0 -0.302450           -0.637351     -0.605480  0.254548       1          0          0         0       0      0            0      1        0          0       0     0        0        0        1       0         0    0        0
28682     2.5 -1.303458            0.213544     -2.690416 -0.393473       0          0          0         0       0      0            0      1        0          0       0     0        1        0        0       0         0    0        0
44690     4.0 -2.304465           -1.306760      0.126197  0.063354       1          1          0         0       1      0            0      1        0          0       0     0        0        0        0       0         0    1        0
43529     4.5 -1.303458            0.723418      0.284038  0.453650       0          0          0         0       0      0            0      1        0          0       0     0        0        0        0       0         0    0        0

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=564)

In [ ]:
from sklearn.ensemble import GradientBoostingRegressor

model = GradientBoostingRegressor()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)

In [ ]:
from sklearn.metrics import mean_squared_error as mse
mse(y_test, y_pred)**0.5

3.0618394883842196e-05

In [ ]:
model.score(X_test,y_test)

0.9999999990751834

In [ ]:
X.shape

(63250, 24)

# Collaborative Rec Sys - Matrix Factorization

In [5]:
ratings= pd.read_csv("/content/drive/Othercomputers/My Laptop/Data Science Studies/GitHub_Desktop/DSML ML2_Unsupervised Learning/ML2_Unsupervised-Learning/ratings.csv")
movies = pd.read_csv("/content/drive/Othercomputers/My Laptop/Data Science Studies/GitHub_Desktop/DSML ML2_Unsupervised Learning/ML2_Unsupervised-Learning/movies.csv")

In [6]:
rm = ratings.pivot(index="userId",
             columns="movieId",
             values="rating").fillna(0)

In [7]:
rm = rm.astype(int)

In [8]:
rm.shape

(668, 10325)

In [9]:
rm.head(5)

movieId,1,2,3,4,5,6,7,8,9,10,...,144482,144656,144976,146344,146656,146684,146878,148238,148626,149532
userId,,,,,,,,,,,,,,,,,,,,,
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,5,0,2,0,3,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,3,0,3,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5,4,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [18]:
((rm==0).count().count() / (668*10325) )*100

0.14970059880239522

In [19]:
# 98.5% is empty : 
# idea is to predict the zeros , based on other details from the data points based on similarity.

### Matrix Factorisation  : 

- Matrix factorization is a class of collaborative filtering algorithms used in recommender systems. 

- Matrix factorization algorithms work by decomposing the user-item interaction matrix into the product of two lower dimensionality rectangular matrices.


- This family of methods became widely known during the Netflix prize challenge due to its effectiveness as reported by Simon Funk in his 2006 blog post, where he shared his findings with the research community.

- The prediction results can be improved by assigning different regularization weights to the latent factors based on items' popularity and users' activeness.

https://en.wikipedia.org/wiki/Matrix_factorization_(recommender_systems)


                  user    item
          r    =    p  *   q
        (m*n)     (m*x)   (x*n)

        predicted Ratings :    

          r'  =  p_user.T . q_item
          ui

        
      How can we learn user and Item condensed Embedding 

      
      min   sum sum [ rij -p_user.T*q_item]**2
      u,i     i  u
      (GD)          (sum of squared errors)

        minimise   (actual - predicted)**2
     users,items

    basically we are trying to reduce out dimentions.



    Facotrisation can be done after a certain period of time 
    but matrix multiplication happens at runtime while predicting

    
    R_item_user = global   +   user    +  item      + dot(Puser.T ,q_item)
                  rating     deviation   deviation
                              from        from
                              global     global

![image.png]()

# Cold start 
- is a potential problem in computer-based information systems which involves a degree of automated data modelling. Specifically, it concerns the issue that the system cannot draw any inferences for users or items about which it has not yet gathered sufficient information.

In [22]:
ratings.sample(2)

       userId  movieId  rating   timestamp
50381     360     2699     3.0  1286595125
22238     164   115210     4.0  1440963079

In [42]:
rm_raw = ratings[['userId', 'movieId', 'rating']].copy()
rm_raw.columns = ['UserId', 'ItemId', 'Rating']  # Lib requires specific column names

In [52]:
rm_raw.nunique()

UserId      668
ItemId    10325
Rating       10
dtype: int64

In [53]:
# !pip install cmfrec
rm_raw.dtypes

UserId      int64
ItemId      int64
Rating    float64
dtype: object

In [44]:
from cmfrec import CMF

model = CMF(k=3, lambda_=0.1, user_bias=False, item_bias=False, verbose=False)
model.fit(rm_raw)

Collective matrix factorization model
(explicit-feedback variant)

In [45]:
rm_raw.shape

(105339, 3)

In [46]:
model.A_

array([[-1.0550873 ,  0.0412095 ,  0.77834815],
       [ 0.519356  ,  0.40093583,  0.84999317],
       [-0.23952663,  0.37213048,  0.59112555],
       ...,
       [-1.0284927 ,  0.24378464,  0.6292355 ],
       [-0.3788216 ,  0.53025246,  0.26887295],
       [-0.80368423, -0.9499607 ,  0.77726233]], dtype=float32)

In [47]:
model.B_

array([[-0.19630846,  0.69072443,  0.45589563],
       [ 1.0571836 ,  0.35641232, -0.5794131 ],
       [-0.16307904,  0.6692471 ,  0.54176795],
       ...,
       [ 0.3652432 ,  0.43864945, -0.3577852 ],
       [-0.17354284, -0.2084211 ,  0.16999935],
       [ 0.00605254,  0.00726895, -0.00592895]], dtype=float32)

In [48]:
model.A_.shape,model.B_.T.shape

((668, 3), (3, 10325))

In [49]:
top_items = model.topN(user=1, n=10)
top_items
# top 10 recommendations for user id 1

array([  8131,    824,   3134,   8253,   3612, 122886,   3469,   1941,
         5637,  48161])

,movieId,title,genres
670,824,Kaspar Hauser (1993),Drama|Mystery
1507,1941,Hamlet (1948),Drama
2508,3134,Grand Illusion (La grande illusion) (1937),Drama|War
2754,3469,Inherit the Wind (1960),Drama
2857,3612,"Slipper and the Rose, The (1976)",Adventure|Musical|Romance
4290,5637,Flirting (1991),Drama
5560,8131,Pursuit of Happiness (2001),Comedy|Romance
5591,8253,Lupin III: The Castle Of Cagliostro (Rupan san...,Action|Adventure|Animation|Comedy|Crime|Mystery
7143,48161,Gridiron Gang (2006),Drama
10158,122886,Star Wars: Episode VII - The Force Awakens (2015),Action|Adventure|Fantasy|Sci-Fi

In [51]:
top_items = model.topN(user=2, n=10)
movies.loc[movies.movieId.isin(top_items)]

,movieId,title,genres
3026,3830,Psycho Beach Party (2000),Comedy|Horror|Thriller
3534,4518,The Lair of the White Worm (1988),Comedy|Horror
5075,6987,"Cabinet of Dr. Caligari, The (Cabinet des Dr. ...",Crime|Fantasy|Horror
5211,7158,House of Sand and Fog (2003),Drama
6337,27592,Sympathy for Mr. Vengeance (Boksuneun naui geo...,Crime|Drama
6702,34542,Grizzly Man (2005),Documentary
7882,62336,FLCL (2000),Animation|Comedy|Fantasy|Sci-Fi
9117,89582,Cold Fish (Tsumetai nettaigyo) (2010),Drama|Thriller
9279,92535,Louis C.K.: Live at the Beacon Theater (2011),Comedy
9454,96832,Holy Motors (2012),Drama|Fantasy|Musical|Mystery|Sci-Fi

In [ ]:
rm__ = np.dot(model.A_, model.B_.T) + model.glob_mean_
mse(rm.values[rm > 0], rm__[rm > 0])**0.5

1.2622586966805192